ci: use AOSS repository
AOSS (https://cloud.google.com/security/products/assured-open-source-software)
provides secure OSS packages

AOSS requires to use a Kokoro custom pool. We use yoshi-ubuntu pool, where
`gcloud components install app-engine-java --quiet` failed with:

```
ERROR: (gcloud.components.install)
You cannot perform this action because the Google Cloud CLI component manager
is disabled for this installation. You can run the following command
to achieve the same result for this installation:

sudo apt-get install google-cloud-cli-app-engine-java
```

Change-Id: Id4befec68295e0207b4161476aaa966bd6ad77b6